name: Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  health_check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check the deployed website URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-z401.onrender.com/version
          max-attempts: 2
          retry-delay: 1s
      - name: Notify Discord on Success
        if: success()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'GitHub ${{ github.actor }} Bot - Health Check'
          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          content: 'Health check passed for Pokedex'
          embed-title: 'Pokedex Health Check'
          embed-color: 3077745
          embed-description: 'URL: https://full-stack-open-pokedex-z401.onrender.com/health'
      - name: Notify Discord on failure
        if: failure()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'GitHub ${{ github.actor }} Bot - Health Check'
          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          content: 'Health check failed for Pokedex'
          embed-title: 'Pokedex Health Check'
          embed-color: 16731196
          embed-description: 'URL https://full-stack-open-pokedex-z401.onrender.com/health'
