name: Test notify issue pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: 'info'
          text: 'A new version of code deployed successfully'
      - name: Debug Webhook Response
        if: always()
        run: |
          curl -i -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d '{"content":"Test message from GitHub Actions for issue"}'
